export const GET_GOODS_REQUEST_STARTED = 'GOODS/GET_GOODS_REQUEST_STARTED'
export const GET_GOODS_REQUEST_SUCCESS = 'GOODS/GET_GOODS_REQUEST_SUCCESS'
export const GET_GOODS_REQUEST_FAILURE = 'GOODS/GET_GOODS_REQUEST_FAILURE'
export const CLEAN_GOODS = 'GOODS/CLEAN_GOODS'

export const ADD_NEW_GOOD_TO_CART = 'CART/ADD_NEW_GOOD_TO_CART'
export const REMOVE_GOOD_FROM_CART = 'CART/REMOVE_GOOD_FROM_CART'
export const REMOVE_GOODS_FROM_CART = 'CART/REMOVE_GOODS_FROM_CART'
export const GET_GOODS_FROM_STORAGE = 'CART/GET_GOODS_FROM_STORAGE'